<?php


/**
 * This class defines the structure of the 'sighting' table.
 *
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Mon Dec 21 09:15:43 2009
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class SightingTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.SightingTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('sighting');
		$this->setPhpName('Sighting');
		$this->setClassname('Sighting');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addForeignKey('RECORD_ID', 'RecordId', 'INTEGER', 'record', 'ID', true, null, null);
		$this->addForeignKey('SPECIE_ID', 'SpecieId', 'INTEGER', 'specie', 'ID', true, null, null);
		$this->addForeignKey('BEHAVIOUR_ID', 'BehaviourId', 'INTEGER', 'behaviour', 'ID', true, null, null);
		$this->addForeignKey('ASSOCIATION_ID', 'AssociationId', 'INTEGER', 'association', 'ID', true, null, null);
		$this->addColumn('ADULTS', 'Adults', 'INTEGER', true, null, null);
		$this->addColumn('JUVENILES', 'Juveniles', 'INTEGER', true, null, null);
		$this->addColumn('CUBS', 'Cubs', 'INTEGER', true, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('Record', 'Record', RelationMap::MANY_TO_ONE, array('record_id' => 'id', ), null, null);
    $this->addRelation('Specie', 'Specie', RelationMap::MANY_TO_ONE, array('specie_id' => 'id', ), null, null);
    $this->addRelation('Behaviour', 'Behaviour', RelationMap::MANY_TO_ONE, array('behaviour_id' => 'id', ), null, null);
    $this->addRelation('Association', 'Association', RelationMap::MANY_TO_ONE, array('association_id' => 'id', ), null, null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // SightingTableMap
