<?php


/**
 * Skeleton subclass for performing query and update operations on the 'news_article_i18n' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Fri Dec 11 16:11:01 2009
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class NewsArticleI18nPeer extends BaseNewsArticleI18nPeer {

} // NewsArticleI18nPeer
