<?php


/**
 * Skeleton subclass for representing a row from the 'news_article' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Fri Dec 11 16:11:00 2009
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class NewsArticle extends BaseNewsArticle {

	/**
	 * Initializes internal state of NewsArticle object.
	 * @see        parent::__construct()
	 */
	public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}
	
	/*
	public function setHeadline($headline, $culture = null)
	{
	  $object = parent::setHeadline($headline, $culture);
	 
	  $object->setSlug(mfText::stripText($this->getHeadline(sfConfig::get('sf_default_culture', 'en'))));
	  return $object;
	}
	*/
	public function save(PropelPDO $con = null)
	{
		$this->setSlug(mfText::stripText($this->getHeadline(sfConfig::get('sf_default_culture', 'en'))));
		
		parent::save($con);
		
		if ( $this->getImage() ){
			WideImage::load(sfConfig::get('sf_upload_dir').'/news/'.$this->getImage())->resize(140, 500)->saveToFile(sfConfig::get('sf_upload_dir').'/news/tn_'.$this->getImage()); 
		}
	}

} // NewsArticle
