<?php


/**
 * Skeleton subclass for performing query and update operations on the 'news_article' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Fri Dec 11 16:11:00 2009
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class NewsArticlePeer extends BaseNewsArticlePeer {
  public static function getPager()
  { 
  	$user = sfContext::getInstance()->getUser();
  	$request = sfContext::getInstance()->getRequest();
  	
  	$pager = NewsArticleQuery::create()->
  	  useNewsArticleI18nQuery()->
  	    filterByCulture($user->getCulture())->
  	  enduser()->
  	  filterByIsPublished(true)->
  	  filterByEnterDate(array('max' => time()))->
  	  filterByExitDate(array('min' => time()))->
      orderByPublishedDate(Criteria::DESC)->
      paginate($request->getRequestParameter('page', 1), 10);
  	return $pager;
  }
} // NewsArticlePeer
