<?php


/**
 * Skeleton subclass for performing query and update operations on the 'record' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Fri Dec 18 17:25:55 2009
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class RecordPeer extends BaseRecordPeer {
	
	public static function doSelectByGeneralInfo() {
		$id = sfContext::getInstance()->getRequest()->getParameter('gi_id');
		$query = RecordQuery::create()
		  ->filterByGeneralInfoId($id)
		  ->paginate();
		return $query;
	}
} // RecordPeer
