<?php


/**
 * Skeleton subclass for representing a row from the 'watch_post' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.0-dev on:
 *
 * Fri Oct 28 19:07:04 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class WatchPost extends BaseWatchPost {
	public function __toString()
  {
    return $this->getName();
  }
} // WatchPost
